version: "2"
run:
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
    json:
      path: stderr
    checkstyle:
      path: report.xml
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - dogsled
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - spancheck
    - staticcheck
    - tagliatelle
    - testifylint
    - unconvert
    - unparam
    - whitespace
    - wrapcheck
    - zerologlint
  disable:
    - rowserrcheck
    - sqlclosecheck
  settings:
    govet:
      settings:
        printf:
          funcs:
            - (github.com/sirupsen/logrus).Infof
            - (github.com/sirupsen/logrus).Warnf
            - (github.com/sirupsen/logrus).Debugf
            - (github.com/sirupsen/logrus).Errorf
            - (github.com/sirupsen/logrus).Fatalf
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/bentoml
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
