apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bento-image-snapshotter.fullname" . }}
  labels:
    {{- include "bento-image-snapshotter.labels" . | nindent 4 }}
data:
  bento-image-snapshotter.service: |-
    [Unit]
    Description=bento image snapshotter
    After=network.target
    Before=containerd.service

    [Service]
    Type=notify
    EnvironmentFile=-/etc/systemd/system/bento-image-snapshotter.service.env
    ExecStart=/usr/bin/bento-image-snapshotter
    Restart=always
    RestartSec=1

    [Install]
    WantedBy=multi-user.target
