apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bento-image-snapshotter.fullname" . }}
  labels:
    {{- include "bento-image-snapshotter.labels" . | nindent 4 }}
stringData:
  bento-image-snapshotter.service.env: |-
    S3_ENDPOINT_URL={{ .Values.s3.endpointURL }}
    AWS_ACCESS_KEY_ID={{ .Values.s3.accessKeyID }}
    AWS_SECRET_ACCESS_KEY={{ .Values.s3.secretAccessKey }}
    ENABLE_RAMFS={{ .Values.enableRamfs }}
