apiVersion: v1
kind: ConfigMap
immutable: false
metadata:
  name: yatai-image-builder-config
  namespace: {{ .Release.Namespace }}
data:
  default_image_builder_container_resources: |
    requests:
      {{- .Values.builder.requests | toYaml | nindent 6 }}
    limits:
      {{- .Values.builder.limits | toYaml | nindent 6 }}
  extra_pod_spec: |
    nodeSelector:
      {{- .Values.builder.nodeSelector | toYaml | nindent 6 }}
    tolerations:
      {{- .Values.builder.tolerations | toYaml | nindent 6 }}
    affinity:
      {{- .Values.builder.affinity | toYaml | nindent 6 }}
