{{- if .Values.builder.serviceAccount.create -}}
{{- range .Values.global.deploymentNamespaces }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "yatai-image-builder.builderServiceAccountName" . }}
  namespace: {{ . }}
  labels:
    {{- include "yatai-image-builder.labels" . | nindent 4 }}
    "yatai.ai/yatai-image-builder-pod": "true"
  {{- with .Values.builder.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
