apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "yatai-image-builder.serviceAccountName" . }}
  namespace: {{ .Values.yataiSystem.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yatai-image-builder.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "yatai-image-builder.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
