apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "yatai-image-builder.yatai-rolename-in-yatai-system-namespace" . }}
  namespace: {{ .Values.global.yataiSystemNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yatai-image-builder.yatai-rolename-in-yatai-system-namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.global.yataiSystemServiceAccountName }}
    namespace: {{ .Values.global.yataiSystemNamespace }}
