{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yatai-image-builder.fullname" . }}
  labels:
    release: prometheus
    {{- include "yatai-image-builder.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "yatai-image-builder.labels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
{{- end }}
