apiVersion: v1
kind: Service
metadata:
  name: {{ include "yatai-image-builder.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yatai-image-builder.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
    name: https
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: metrics
  selector:
    {{- include "yatai-image-builder.selectorLabels" . | nindent 4 }}
